// Generated by CoffeeScript 1.6.3
(function() {
  var JsonPostHandler, http, request, util;

  util = require('util');

  http = require('http');

  request = require('request');

  exports.JsonPostHandler = JsonPostHandler = function() {
    this.retryCounts = {};
    return this;
  };

  JsonPostHandler.prototype.handleTask = function(task) {
    var json, params, self;
    self = this;
    params = task.params;
    json = {
      payload: params.payload
    };
    if (params.auth) {
      json.auth = params.auth;
    }
    return request({
      method: 'POST',
      uri: params.postUrl,
      json: json
    }, function(error, response, body) {
      if (error) {
        util.log(error);
        return task.done();
      } else if (response.statusCode === 200) {
        return task.done();
      } else {
        return self.retry(task);
      }
    });
  };

  JsonPostHandler.prototype.retry = function(task) {
    var retryCount;
    retryCount = this.retryCounts[task.id] || 0;
    if (retryCount < 5) {
      task.retry(60);
      return this.retryCounts[task.id] = retryCount + 1;
    } else {
      return task.done();
    }
  };

}).call(this);
